version: '3'

services:
  app-dev:
    image: rohitkas/app-dev:latest
    container_name: app-dev
    restart: always
    ports:
      - "80:7071"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/employees
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb-data:/data/db


volumes:
  mongodb-data:
