version: '3'

services:
  app-pro:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "443:7071"
    volumes:
      - /ssl:/app/ssl
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/employees
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
