version: '3'

services:
  app_front:
    build:
     context: ./payroll-front
     dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - app-back

  app-back:
    build: 
     context: .
     dockerfile: Dockerfile
    ports:
      - "7074:7074"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/employees
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  nginx:
    image: nginx
    ports:
      - "443:443"
    volumes:
      # - ./ssl:/etc/nginx/ssl:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app_front

volumes:
  mongodb-data:
