version: '3'

services:
   app-prod:
    image: rohitkas/app-prod:${{github.sha }}
    container_name: zecdata-pay
    restart: always
    ports:
      - "80:7071"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/employees
    depends_on:
      - mongodb
  #    - frontend

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

 # frontend:
 #   build: ./payroll-front
 #  ports:
  #    - "3000:3000"

volumes:
  mongodb-data:
