version: '3'

services:
  app_front:
    image: rohitkas/payroll-front
    ports:
      - "3000:3000"
    depends_on:
      - app-back

  app-back:
    image: rohitkas/payroll-back
    restart: always
    ports:
      - "7074:7074"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/employees
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app_front

volumes:
  mongodb-data:
