version: '3'

services:
     app:
     build: 
      context: .
     ports:
       - "7071:7071"
 
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/employees
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
