version: '3'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "7071:7071"
  frontend:
     build:
      context: ./payroll-front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/employees
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
