name: Node.js CD to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build_package:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    

    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
       registry: docker.io
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
       
    - name: Build Docker images
      run: docker-compose build
    - name: Push Docker images
      run: docker-compose push
       
  Deploy:
    needs: build_package
    runs-on: ubuntu-latest
    
    steps:
     - name: Deploy application to droplet
       uses: webfactory/ssh-agent@v0.5.0
       with:
        ssh-private-key: ${{ secrets.DROPLET_SSH_KEY }}
        
     - name: Deploy application to Droplet
       run: |
         
            ssh root@174.138.123.90 'cd /app && git pull && docker-compose down && docker-compose up -d'

    


        
    
   
   

