name: CD

on:
  push:
    branches:
      - main
      - dev
      
env:
  PROD-DROPLATE-IP: ${{ secrets.DROPLET_IP }}
  PROD-PASSWORD: ${{ secrets.DROPLET2_PASSWORD }}
  DEV-DROPLATE-IP: ${{ secrets.DEV_DROPLET_IP }}
  DEV-PASSWORD: ${{ secrets.DROPLET2_PASSWORD }}
  

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
       
#   build-dev:
#       if: github.ref == 'refs/heads/dev'
#       needs: Login-dockerhub
#       runs-on: self-hosted
#       steps:   
#       - name: Build and push Docker image
#         uses: docker/build-push-action@v2
#         with:
#          context: .
#          Dockerfile: Dockerfile.dev
#          push: true
#          tags: rohitkas/app-dev:${{ github.sha }}
        
#   deploy-dev:
#      if: github.ref == 'refs/heads/dev'
#      needs: build-dev
#      runs-on: self-hosted
     
#      steps:
#       - name: Deploy to dev
#         uses: appleboy/ssh-action@master
#         with:
#          host: ${{ env.DEV-DROPLATE-IP }}
#          username: root
#          password: ${{ env.DEV-PASSWORD }}
#          script: |
#           cd  ~/zd-payroll
#           git pull origin dev
#           docker-compose -f docker-compose.dev.yml down
#           docker rmi zd-payroll_app-dev
#           docker-compose -f docker-compose.dev.yml up -d

          
#   build-prod:
#       if: github.ref == 'refs/heads/main'
#       needs: build
#       runs-on: self-hosted
#       steps:
#        - name: Login to Docker Hub
#          uses: docker/login-action@v1
#          with:
#           registry: docker.io
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#        - name: Build Docker image back
#          run: |
#            docker build -t payroll-back .
#            docker push  rohitkas/payroll-back
#        - name: Build Docker image back
#          run: |
#            docker build -t payroll-front .
#            docker push  rohitkas/payroll-front
        
  deploy-prod:
     if: github.ref == 'refs/heads/main'
     runs-on: self-hosted
     steps:
      - name: Deploy to prod
        uses: appleboy/ssh-action@master
        with:
         host: ${{ env.PROD-DROPLATE-IP }}
         username: root
         password: ${{ env.PROD-PASSWORD }}
         script: |
          cd ~/zd-payroll-1
          git pull
          docker-compose -f docker-compose.yml down
          docker rmi zd-payroll-1-app_front zd-payroll-1-app-back
          docker-compose -f docker-compose.yml up -d
