name: CD

on:
  push:
    branches:
      - main
      
jobs:
  Login-dockerhub:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build frontend
      working-directory: ./payroll-front
      run: npm install && npm run build
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
       
  build-dev:
      if: github.ref == 'refs/heads/dev'
      needs: Login-dockerhub
      runs-on: self-hosted
      steps:   
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
         context: .
         Dockerfile: Dockerfile.dev
         push: true
         tags: rohitkas/app-dev:${{ github.sha }}
        
  deploy-dev:
     if: github.ref == 'refs/heads/dev'
     needs: build-dev
     runs-on: self-hosted
     
     steps:
      - name: Deploy to dev
        uses: appleboy/ssh-action@master
        with:
         host: ${{ env.DEV-DROPLATE-IP }}
         username: root
         password: ${{ env.DEV-PASSWORD }}
         script: |
          cd  ~/zd-payroll
          git pull origin dev
          docker-compose -f docker-compose.dev.yml down
          docker rmi zd-payroll_app-dev
          docker-compose -f docker-compose.dev.yml up -d

    - name: Build Docker images
      run: |
        docker build -t zd-payroll .
        docker build -t zd-payroll-frontend ./payroll-front

    - name: Push Docker images to Digital Ocean registry
      run: |
        docker tag zd-payroll registry.digitalocean.com/zd-payroll/zd-payroll:latest && docker push registry.digitalocean.com/zd-payroll/zd-payroll:latest
        docker tag zd-payroll-frontend registry.digitalocean.com/zd-payroll/zd-payroll-frontend:latest && docker push registry.digitalocean.com/zd-payroll/zd-payroll-frontend:latest



    - name: Deploy to Droplet
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: root
        password: ${{ secrets.DROPLET2_PASSWORD }}
        ports: 22
        script: |
          cd  ~/zd-payroll
          docker-compose down
          docker-compose up -d
