name: Node.js CD to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build_package:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
       registry: docker.io
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}


        
    
   
   

