name: Node.js CD to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build_package:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    

    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
       registry: docker.io
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
       
    - name: build and push docker image
      uses: actions/build-push-action@v2
      with:
       context: .
       push: true
       tag: rohitkas/zecdatamain:latest
       
  Deploy:
    runs-on: ubuntu-latest
    
    steps:
     - name: Deploy application to droplet
       uses: actions/ssh-action@master
       with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USERNAME }}
        key: ${{ secrets.DROPLET_PRIVATE_KEY }}
        
     - name:  deploy docker compose
       run: | 
          docker-compose down || true   &&
          docker-compose up   || true
           
     
    


        
    
   
   

