name: CD

on:
  push:
    branches:
      - main
      - dev
      
env:
  PROD-DROPLATE-IP: ${{ secrets.DROPLET_IP }}
  PROD-PASSWORD: ${{ secrets.DROPLET2_PASSWORD }}
  DEV-DROPLATE-IP: ${{ secrets.DEV_DROPLET_IP }}
  DEV-PASSWORD: ${{ secrets.DROPLET2_PASSWORD }}
  

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
       registry: docker.io
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
<<<<<<< HEAD

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: rohitkas/app:latest
=======
       
  build-dev:
      if: github.ref == 'refs/heads/dev'
      needs: Login-dockerhub
      runs-on: self-hosted
      steps:   
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
         context: .
         Dockerfile: Dockerfile.dev
         push: true
         tags: rohitkas/app-dev:${{ github.sha }}
>>>>>>> 96021a3caa3ab0631a0c6915b515dae2a6cd63e1
        
  deploy-dev:
     if: github.ref == 'refs/heads/dev'
     needs: build
     runs-on: self-hosted
     
     steps:
      - name: Deploy to dev
        uses: appleboy/ssh-action@master
        with:
         host: ${{ env.DEV-DROPLATE-IP }}
         username: root
         password: ${{ env.DEV-PASSWORD }}
         script: |
          cd  ~/zd-payroll
<<<<<<< HEAD
          git pull 
          docker-compose down
          docker-compose up -d
=======
          docker-compose -f docker-compose.dev.yml pull 
          docker-compose -f docker-compose.dev.yml down 
          docker rmi rohitkas/app-dev
          docker-compose -f docker-compose.dev.yml pull 
          docker-compose -f docker-compose.dev.yml up -d

          
  build-prod:
      if: github.ref == 'refs/heads/main'
      needs: Login-dockerhub
      runs-on: self-hosted
      steps:   
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
         context: .
         push: true
         tags: rohitkas/app-prod:${{ github.sha }}
        
>>>>>>> 96021a3caa3ab0631a0c6915b515dae2a6cd63e1
        
  deploy-prod:
     if: github.ref == 'refs/heads/main'
     needs: build
     runs-on: self-hosted
     
     steps:
      - name: Deploy to prod
        uses: appleboy/ssh-action@master
        with:
         host: ${{ env.PROD-DROPLATE-IP }}
         username: root
         password: ${{ env.PROD-PASSWORD }}
         script: |
          cd  ~/zd-payroll
<<<<<<< HEAD
          docker-compose pull
          docker-compose down
          docker rmi zd-payroll_app 
=======
          docker-compose down
          docker rmi rohitkas/app-prod
          docker-compose pull 
>>>>>>> 96021a3caa3ab0631a0c6915b515dae2a6cd63e1
          docker-compose up -d
