name: Node.js CD to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build_package:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
       registry: docker.io
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
       
    - name: Build Docker images
      run: docker-compose build
    - name: Push Docker images
      run: docker-compose push
       
  Deploy:
    needs: build_package
    runs-on: ubuntu-latest
    
    steps:
     - name: Set up SSH
       uses: appleboy/ssh-action@master
       with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USERNAME }}
        key: ${{ secrets.DROPLET_PRIVATE_KEY }}

        script: |
       
          ssh ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_IP }} 'git pull && docker-compose down && docker-compose up -d'
    


        
    
   
   

